# Generated by Django 5.2.8 on 2025-11-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('media_type', models.CharField(choices=[('video', 'Vidéo'), ('audio', 'Audio'), ('image', 'Image')], max_length=10)),
                ('quality', models.CharField(choices=[('best', 'Meilleure'), ('1080', '1080p'), ('720', '720p'), ('480', '480p')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
