# Generated by Django 5.2.8 on 2025-11-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediadownload',
            options={'verbose_name': 'Téléchargement', 'verbose_name_plural': 'Téléchargements'},
        ),
        migrations.AlterField(
            model_name='mediadownload',
            name='media_type',
            field=models.CharField(choices=[('video', 'Vidéo'), ('audio', 'Audio'), ('miniature', 'Miniature')], default='video', max_length=10),
        ),
        migrations.AlterField(
            model_name='mediadownload',
            name='quality',
            field=models.CharField(choices=[('best', 'Meilleure'), ('1080', 'Haute'), ('720', 'Moyenne'), ('480', 'Basique')], default='best', max_length=10),
        ),
    ]
